region                 = "us-ashburn-1"
tenancy_ocid           = "ocid1.tenancy.oc1..aaaaaaaaa3qmjxr43tjexx75r6gwk6vjw22ermohbw2vbxyhczksgjir7xdq"
apps_compartment_ocid  = "ocid1.compartment.oc1..aaaaaaaabf3wd2xtxwxmxtc4ymsklrhsfwsvysdo2bh77mntrypde5n5bqma"
vcn_ocid               = "ocid1.vcn.oc1.iad.amaaaaaac3adhhqaswr7zncbw3v3aqlszozpizsnvazklx3toldqleeiun2a"
private_route_table_ocid = "ocid1.routetable.oc1.iad.aaaaaaaa5gaadaeutuxelszh2u72deueuj6ivgkae7o2tsqanbr6iozmh2aq"
security_list_ocid     = "ocid1.securitylist.oc1.iad.aaaaaaaawgodbr7typ2hq3jfvfizkuqmegkcogmb4pzzmbegq6jgztqtw7xq"