region                 = "us-ashburn-1"
tenancy_ocid           = "ocid1.tenancy.oc1..xxxx"
apps_compartment_ocid  = "ocid1.compartment.oc1..xxxx"
vcn_ocid               = "ocid1.vcn.oc1.ca-toronto-1.xxxx"
private_route_table_ocid = "ocid1.routetable.oc1.ca-toronto-1.xxxx"
security_list_ocid     = "ocid1.securitylist.oc1.ca-toronto-1.xxxx"
