name: Download GitHub OIDC JWT

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  get-jwt:
    runs-on: ubuntu-latest

    env:
      CLIENT_ID: 8aa264f421d646e98699b716b2e9b72e  # Used if you want to change audience

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Request GitHub OIDC token and save to file
        run: |
          TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=github-actions" \
            | jq -r .value)

          echo "$TOKEN" > jwt_token.txt

      - name: Move JWT to .oci/id-token.jwt
        run: |
          mkdir -p .oci
          mv jwt_token.txt .oci/id-token.jwt

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install custom OCI SDK
        run: pip install git+https://github.com/balajepalli84/oci-python-sdk-token-exchange.git

      - name: Run test script
        env:
          OCI_DOMAIN_ID: idcs-8dd307747946491cbfe1b7a3f063db0d
          OCI_CLIENT_ID: 8aa264f421d646e98699b716b2e9b72e
          OCI_CLIENT_SECRET: idcscs-59183ab6-657c-4a24-ad24-ffae6c8bc061
          OCI_REGION: us-ashburn-1
        run: python scripts/test_sdk.py
