name: Token Exchange Test - Get_JWT_from PY 

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  get-jwt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: List files in workspace
        run: ls -la

      - name: Run get_jwt.py
        run: python get_jwt.py

      - name: Upload JWT as artifact
        uses: actions/upload-artifact@v4
        with:
          name: oidc-jwt
          path: oidc_jwt.txt
