name: Get GitHub OIDC JWT

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  get-jwt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: List files in workspace
        run: |
          echo "Listing files in workspace:"
          ls -la
          echo "Listing files in .github/workflows:"
          ls -la .github/workflows

      - name: Run get_jwt.py
        run: python get_jwt.py
