name: Create OCI VCN With Terraform

on:
  workflow_dispatch:

permissions:
  id-token: write       # Required for GitHub OIDC
  contents: read

jobs: 
  OCI-IaC-Deployment:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4

      - name: 'Request GitHub OIDC Token'
        id: get-jwt
        run: |
          echo "Requesting OIDC token from GitHub..."
          curl -sLS -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=oci" > id-token.json
          cat id-token.json

      - name: 'Exchange OIDC token with OCI'
        id: get-oci-token
        run: |
          JWT=$(jq -r '.value' id-token.json)

          echo "Setting up temporary OCI config using OIDC..."

          mkdir -p ~/.oci

          cat <<EOF > ~/.oci/config
          [DEFAULT]
          region=${{ secrets.OCI_REGION }}
          delegation_token_file=~/.oci/token
          EOF

          echo "$JWT" > ~/.oci/token
          chmod 600 ~/.oci/config ~/.oci/token

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v3

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve -input=false
