name: Print GitHub OIDC Token

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs: 
  Print-JWT:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4

      - name: 'Request GitHub OIDC Token'
        id: get-jwt
        run: |
          echo "Fetching OIDC token from GitHub..."

          curl -sSL -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=oci" > id-token.json

          echo "Decoded JWT (Header & Payload):"
          JWT=$(jq -r '.value' id-token.json)

          echo "==== HEADER ===="
          echo "$JWT" | cut -d '.' -f1 | base64 -d

          echo "==== PAYLOAD ===="
          echo "$JWT" | cut -d '.' -f2 | base64 -d

          echo "==== RAW JWT ===="
          echo "$JWT"
