name: 11_SDK_Test OCI Token Exchange

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:

jobs:
  run-sdk-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get OIDC Token
        id: oidc
        uses: actions/github-script@v7
        with:
          script: |
            const idToken = await core.getIDToken("oracle-cloud");
            core.setOutput("id_token", idToken);

      - name: Write OIDC token to file
        run: |
          mkdir -p .oci
          echo "${{ steps.oidc.outputs.id_token }}" > .oci/id-token.jwt

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install custom OCI SDK
        run: pip install git+https://github.com/balajepalli84/oci-python-sdk-token-exchange.git

      - name: Run test script
        env:
          OCI_DOMAIN_ID: idcs-8dd307747946491cbfe1b7a3f063db0d
          OCI_CLIENT_ID: 8aa264f421d646e98699b716b2e9b72e
          OCI_CLIENT_SECRET: idcscs-59183ab6-657c-4a24-ad24-ffae6c8bc061
          OCI_REGION: us-ashburn-1
        run: python scripts/test_sdk.py
