name: 11_Run Token Exchange SDK Test with GitHub OIDC JWT

on:
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      CLIENT_ID: ${{ secrets.OCI_CLIENT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e git+https://github.com/balajepalli84/oci-python-sdk-token-exchange#egg=oci

      - name: Fetch GitHub OIDC Token
        id: jwt
        run: |
          mkdir -p .oci
          curl -sSL -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=${CLIENT_ID}" > id-token.json

          JWT=$(jq -r '.value' id-token.json)
          echo "$JWT" > .oci/id-token.jwt
          echo "jwt=$JWT" >> $GITHUB_OUTPUT

      - name: Run test_sdk.py
        env:
          OCI_JWT: ${{ steps.jwt.outputs.jwt }}
          OCI_DOMAIN_ID: ${{ secrets.OCI_DOMAIN_ID }}
          OCI_CLIENT_ID: ${{ secrets.OCI_CLIENT_ID }}
          OCI_CLIENT_SECRET: ${{ secrets.OCI_CLIENT_SECRET }}
          OCI_REGION: us-ashburn-1
          OCI_SECRET_ID: ${{ secrets.OCI_SECRET_ID }}
        run: |
          python scripts/test_sdk.py
